### ISSUE TITLE
1.11 localztion 

### ISSUE THREAD

**Issue by Mattabase** [davqvist/CustomAchievements#6] opened 2017-07-01 18:25 UTC
https://goo.gl/bNfXpN

While using the mod in 1.11 this happens, I had to localize it myself for each one to get it to work.

**Comment by davqvist** [comment] 2017-07-02 03:17
Not reproducible for me. What do you have your language set to?

**Comment by Mattabase** [comment] 2017-07-07 17:11
English (US)

**Comment by davqvist** [comment] 2017-07-11 17:00
Can't really replicate that. Can you pastebin the latest.log please?

**Comment by Mattabase** [comment] 2017-07-11 18:31
https://goo.gl/YWrJzr

**Comment by davqvist** [comment] 2017-07-11 19:00
Doesn't make any sense to me right now, as no logs from CA are generated for some weird reason.
It is saying though that the Achievement Names are loaded in line 66.
Probably some mod messing with resources. I can see CustomOverridingResources, maybe that's it, but don't know from what mod that is. Do you have any ideas?

I would appreciate if you could maybe test only CA and if it works with only CA, maybe track down which mod is causing that by slowly adding/disabling mods until it works/stops working.

**Comment by Mattabase** [comment] 2017-07-11 19:37
Alrighty, I will start doing some testing now.

**Comment by Mattabase** [comment] 2017-07-11 19:55
I tracked down the mod causing the problem. 

https://minecraft.curseforge.com/projects/randomtweaks

**Comment by TheRandomLabs** [comment] 2017-07-11 20:25
Sorry about that. I'll have a look at it soon.

**Comment by davqvist** [comment] 2017-08-29 20:25
Closing this now as this seems to be resolved.

**Closed as completed by davqvist** 2017-08-29 20:25 UTC
Labels: mod interaction
