### ISSUE TITLE
Compatibility: Rendering crash with The One Probe

### ISSUE THREAD

**Issue by leagris** [davqvist/CustomAchievements#3] opened 2017-05-19 18:54 UTC
##### Versions

- Custom Achievements 1.11.2-0.3.0
- The One Probe 1.1x-1.4.7
- Minecraft Forge 13.20.0.2296

##### `NullPointerException` Crash

While breaking out a crafting-table trophy, just as the break animation ends and the trophy block is about to turn into an item..

[crash-2017-05-19_20.39.40-client.txt](https://gist.github.com/leagris/54a652b108e8c7f0e3792f03891c26ce)

See: https://github.com/McJty/TheOneProbe/issues/163

**Comment by davqvist** [comment] 2017-05-19 19:09
Probably an error on my side, I already a similar issue in 1.10.2 which I was sure I fixed, but I maybe didn't or it got reintroduced in 1.11. Thanks for reporting.

**Comment by davqvist** [comment] 2017-05-19 20:45
Can't replicate. With what tool did you break the Crafting Table? Did you change the customachievements.json? If yes, can you pastebin it?

**Comment by leagris** [comment] 2017-05-19 20:58
Broke it bare hands.
Was initial run of the mod, new map.

**Comment by davqvist** [comment] 2017-05-19 21:21
Hm, can't replicate it still even with breaking with bare hands.
Can you try yourself another time in another test world if you can replicate it?
If yes, please tell me exactly what you have done, step by step, and give me your modlist.
I appreciate it.

**Comment by leagris** [comment] 2017-05-19 23:21
Reproduced it again, without optifine to be sure.

See our modlist here: http://rawgit.com/Beyond-Reality/Beyond-Realty-Farscapes/master/modlist.html

**Comment by leagris** [comment] 2017-05-19 23:39
I tested it in two different worlds.
The first one Had crashes always when breaking trophy
Not that I earned 3 trophy for the crafting table 1 each time I broke/placed it

I continue investigations

**Comment by leagris** [comment] 2017-05-19 23:56
@davqvist I think I have identified the bug trigger.

- Craft a crafting-table
- Obtain Trophy
- Place and break, pickup crafting-table
- Obtain 2nd same Trophy
- Place a Trophy
- Break trophy, once you finish breaking it ⇒ CRASH

So it might be related to breaking a Trophy while having same Trophy in your inventory.
Also I am not sure the achievement's Trophy should trigger multiple-times. Sound more like a bug. Is it intentional?

**Comment by davqvist** [comment] 2017-05-20 08:25
I still can't replicate but I'm pretty sure what the problem is anyway.
Triggering trophies multiple times is of course not intended and a bug in the port.

Both are fixed in 0.3.1
https://github.com/davqvist/CustomAchievements/commit/cafb67f8236bf0d4d96d6fb588a5b004da856d9c

**Closed as completed by davqvist** 2017-05-20 08:25 UTC
